apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-devops
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: php-devops
  template:
    metadata:
      labels:
        app: php-devops
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      containers:
      - name: php-devops
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

