apiVersion: v1
kind: Service
metadata:
  name: php-devops-service
spec:
  selector:
    app: php-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
