plugin: amazon.aws.aws_ec2
aws_profile: "php-devops"
regions:
 - us-east-2
keyed_groups:
  - key: tag:Name 
    prefix: tag_Name_
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
hostvars: 
  - host: "*"
    vars: 
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "~/.ssh/php-devops.pem"
compose:
  ansible_host: public_ip_address