image:
  repository: 646304591001.dkr.ecr.us-east-2.amazonaws.com/samy-ecr
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
replicaCount: 1
rbac:
  create: true
  serviceAccountName: php-devops-sa

networkPolicy:
  enabled: true