image:
  repository: 646304591001.dkr.ecr.us-east-2.amazonaws.com/samy-ecr
  tag: latest
  pullPolicy: IfNotPresent
rbac:
  create: true
  serviceAccountName: app-serviceaccount

networkPolicy:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
