image:
  repository: 646304591001.dkr.ecr.us-east-2.amazonaws.com/samy-ecr
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
replicaCount: 3
rbac:
  create: true
  serviceAccountName: php-devops-sa

networkPolicy:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
