image:
  repository: 646304591001.dkr.ecr.us-east-2.amazonaws.com/samy-ecr
  tag: latest
  pullPolicy: IfNotPresent
rbac:
  create: true
  serviceAccountName: app-serviceaccount

networkPolicy:
  enabled: true